/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   about-arc-electron.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../arc-settings-panel-mixin/arc-settings-panel-mixin.d.ts" />
/// <reference path="../iron-icon/iron-icon.d.ts" />
/// <reference path="../iron-pages/iron-pages.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../paper-toggle-button/paper-toggle-button.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-styles/shadow.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />

declare namespace UiElements {

  /**
   * `about-arc-electron`
   *
   * About screen for ARC electron
   *
   * ## Styling
   *
   * `<about-arc-electron>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--about-arc-electron` | Mixin applied to this elment | `{}`
   */
  class AboutArcElectron extends
    ArcComponents.ArcSettingsPanelMixin(
    Object) {

    /**
     * Current version of the application
     */
    appVersion: string|null|undefined;

    /**
     * page of the update status label
     */
    updateStatePage: number|null|undefined;

    /**
     * State of auto update setting.
     */
    autoUpdate: boolean|null|undefined;

    /**
     * True to indicate that update is being checked or downloaded
     */
    updateProgress: boolean|null|undefined;

    /**
     * True to indicate that the update is ready to install
     */
    updateDownloaded: boolean|null|undefined;

    /**
     * Indicates that error has been reported.
     */
    isError: boolean|null|undefined;

    /**
     * Associated message with current error code.
     */
    errorMessage: string|null|undefined;
    errorCode: string|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _processValues(values: any): any;
    _setSettings(values: any): void;
    _autoUpdateChanged(value: any): void;
    _settingsChanged(key: any, value: any): void;
    _checkingUpdateHandler(): void;
    _updateAvailableHandler(): void;
    _downloadingHandler(): void;
    _updateNotAvailableHandler(): void;
    _updateErrorHandler(e: any, data: any): void;
    _downloadedHandler(): void;
    _createErrorMessage(code: any): void;
    updateCheck(): void;
    updateInstall(): void;
    openNotes(e: any): void;
  }
}

interface HTMLElementTagNameMap {
  "about-arc-electron": UiElements.AboutArcElectron;
}
